# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HousePricePrediction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HousePricePrediction
  pod 'PickerView'
  pod 'IQKeyboardManagerSwift'
  pod 'SPPermissions/Notification'
  pod 'SPPermissions/Location'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'CDAlertView'
end
